const services = [
  {
    title: 'Cherche cat sitting',
    description: 'Bonjour, je cherche à faire garder mon chat Milo pendant mes vacances',
    type: 'Demande',
    category: 'Animaux',
    pc: '58900',
    image: '',
    active: 'Yes',
    created_by: 'Djypi',
    updated_by: '',
  },
  {
    title: 'Demande cours banjo',
    description: 'Je souhaite prendre des cours particuliers de banjo, je débute',
    type: 'Demande',
    category: 'Cours',
    pc: '62230',
    image: '',
    active: 'Yes',
    created_by: 'Mister Romain',
    updated_by: '',
  },
  {
    title: 'Propose covoiturage',
    description: 'Je vous propose de partager avec moi les petits trajets du quotidien',
    type: 'Proposition',
    category: 'Covoiturage',
    pc: '95147',
    image: '',
    active: 'Yes',
    created_by: 'Olive',
    updated_by: '',
  },
  {
    title: 'Propose covoiturage2',
    description: 'Je vous propose de partager avec moi les petits trajets du quotidien',
    type: 'Proposition',
    category: 'Covoiturage',
    pc: '02368',
    image: '',
    active: 'Yes',
    created_by: 'Olive',
    updated_by: '',
  },
  {
    title: 'Propose covoiturage3',
    description: 'Je vous propose de partager avec moi les petits trajets du quotidien',
    type: 'Proposition',
    category: 'Covoiturage',
    pc: '15007',
    image: '',
    active: 'Yes',
    created_by: 'Olive',
    updated_by: '',
  },
  {
    title: 'Propose covoiturage4',
    description: 'Je vous propose de partager avec moi les petits trajets du quotidien',
    type: 'Proposition',
    category: 'Covoiturage',
    pc: '69420',
    image: '',
    active: 'Yes',
    created_by: 'Olive',
    updated_by: '',
  },
  {
    title: 'Propose covoiturage5',
    description: 'Je vous propose de partager avec moi les petits trajets du quotidien',
    type: 'Proposition',
    category: 'Covoiturage',
    pc: '64752',
    image: '',
    active: 'Yes',
    created_by: 'Olive',
    updated_by: '',
  },
  {
    title: 'Propose covoiturage6',
    description: 'Je vous propose de partager avec moi les petits trajets du quotidien',
    type: 'Demande',
    category: 'Covoiturage',
    pc: '33500',
    image: '',
    active: 'Yes',
    created_by: 'Olive',
    updated_by: '',
  },
  {
    title: 'Propose covoiturage7',
    description: 'Je vous propose de partager avec moi les petits trajets du quotidien',
    type: 'Proposition',
    category: 'Covoiturage',
    pc: '18900',
    image: '',
    active: 'Yes',
    created_by: 'Olive',
    updated_by: '',
  },
  {
    title: 'Propose covoiturage8',
    description: 'Je vous propose de partager avec moi les petits trajets du quotidien',
    type: 'Proposition',
    category: 'Covoiturage',
    pc: '85900',
    image: '',
    active: 'Yes',
    created_by: 'Olive',
    updated_by: '',
  },
  {
    title: 'Propose covoiturage9',
    description: 'Je vous propose de partager avec moi les petits trajets du quotidien',
    type: 'Proposition',
    category: 'Covoiturage',
    pc: '94200',
    image: '',
    active: 'Yes',
    created_by: 'Olive',
    updated_by: '',
  },

];

export default services;
