const services = [
  {
    title: 'Cherche cat sitting',
    description: 'Bonjour, je cherche à faire garder mon chat Milo pendant mes vacances',
    type: 'Animaux',
    image: '',
    active: 'Yes',
    created_by: 'Djypi',
    updated_by: '',
  },
  {
    title: 'Demande cours banjo',
    description: 'Je souhaite prendre des cours particuliers de banjo, je débute',
    type: 'Cours',
    image: '',
    active: 'Yes',
    created_by: 'Mister Romain',
    updated_by: '',
  },
  {
    title: 'Propose covoiturage',
    description: 'Je vous propose de partager avec moi les petits trajets du quotidien',
    type: 'Covoiturage',
    image: '',
    active: 'Yes',
    created_by: 'Olive',
    updated_by: '',
  },
  {
    title: 'Propose covoiturage2',
    description: 'Je vous propose de partager avec moi les petits trajets du quotidien',
    type: 'Covoiturage',
    image: '',
    active: 'Yes',
    created_by: 'Olive',
    updated_by: '',
  },
  {
    title: 'Propose covoiturage3',
    description: 'Je vous propose de partager avec moi les petits trajets du quotidien',
    type: 'Covoiturage',
    image: '',
    active: 'Yes',
    created_by: 'Olive',
    updated_by: '',
  },
  {
    title: 'Propose covoiturage4',
    description: 'Je vous propose de partager avec moi les petits trajets du quotidien',
    type: 'Covoiturage',
    image: '',
    active: 'Yes',
    created_by: 'Olive',
    updated_by: '',
  },
  {
    title: 'Propose covoiturage5',
    description: 'Je vous propose de partager avec moi les petits trajets du quotidien',
    type: 'Covoiturage',
    image: '',
    active: 'Yes',
    created_by: 'Olive',
    updated_by: '',
  },
  {
    title: 'Propose covoiturage6',
    description: 'Je vous propose de partager avec moi les petits trajets du quotidien',
    type: 'Covoiturage',
    image: '',
    active: 'Yes',
    created_by: 'Olive',
    updated_by: '',
  },
  {
    title: 'Propose covoiturage7',
    description: 'Je vous propose de partager avec moi les petits trajets du quotidien',
    type: 'Covoiturage',
    image: '',
    active: 'Yes',
    created_by: 'Olive',
    updated_by: '',
  },
  {
    title: 'Propose covoiturage8',
    description: 'Je vous propose de partager avec moi les petits trajets du quotidien',
    type: 'Covoiturage',
    image: '',
    active: 'Yes',
    created_by: 'Olive',
    updated_by: '',
  },
  {
    title: 'Propose covoiturage9',
    description: 'Je vous propose de partager avec moi les petits trajets du quotidien',
    type: 'Covoiturage',
    image: '',
    active: 'Yes',
    created_by: 'Olive',
    updated_by: '',
  },

];

export default services;
