const services = [
  {
    title: 'Cherche cat sitting',
    body: 'Bonjour, je cherche à faire garder mon chat Milo pendant mes vacances',
    type: false,
    category: 'Animaux',
    pc: '02368',
    image: '',
    active: 'Yes',
    createdAT: "16 Avril 2020",
    created_by: 'Djypi',
    updated_by: '',
  },
  {
    title: 'Demande cours banjo',
    body: 'Je souhaite prendre des cours particuliers de banjo, je débute',
    type: false,
    category: 'Cours',
    pc: '17005',
    image: '',
    active: 'Yes',
    createdAT: "16 Avril 2020",
    created_by: 'Mister Romain',
    updated_by: '',
  },
  {
    title: 'Propose covoiturage',
    body: 'Je vous propose de partager avec moi les petits trajets du quotidien',
    type: false,
    category: 'Covoiturage',
    pc: '78025',
    image: '',
    active: 'Yes',
    createdAT: "16 Avril 2020",
    created_by: 'Olive',
    updated_by: '',
  },
];

export default services;
