easy_admin:
    site_name: "O'rinjin"
    entities:
            User:
                class: App\Entity\User
                label: 'Utilisateur'
                form:
                    fields: ['email', 'firstname', 'lastname' ]
                list:
                    fields:
                        - email
                        - firstname
                        - lastname
                        - { property: "updatedAt", label: "Mis à jour le" }

    #    - App\Entity\Comment
    #    - App\Entity\Service
    #    - App\Entity\ServiceCategory
    #    - App\Entity\User
